const STORE='worrySeedsV1';
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
let seeds=[];let filter='all';let currentSeed=null;let recorder=null;let chunks=[];let timer=null;let seconds=0;let pendingAudio=null;let recordingRequested=false;

function uid(){return `${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function addDays(n){const d=new Date();d.setDate(d.getDate()+Number(n));return d.toISOString()}
function fmt(iso){return new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric'}).format(new Date(iso))}
function stage(seed){if(seed.status==='fruited')return['已经结果','♧'];const logs=seed.growthLogs?.length||0;if(logs>=3)return['枝叶渐丰','♧'];if(logs>=1)return['长出新叶','⌁'];return['刚刚发芽','⌁']}
function save(){localStorage.setItem(STORE,JSON.stringify(seeds));render()}
function load(){try{seeds=JSON.parse(localStorage.getItem(STORE)||'[]')}catch{seeds=[]}if(!seeds.length)migrateLegacy();render()}
function migrateLegacy(){const now=new Date().toISOString();let imported=[];try{const bottles=JSON.parse(localStorage.getItem('worryBottles')||'[]');imported.push(...bottles.map(b=>({id:`bottle-${b.id||uid()}`,title:b.title||'一颗旧种子',content:b.content||'',tag:'其他',intensity:b.intensity||2,createdAt:b.createdAt||now,nextReviewAt:b.sealUntil||now,status:b.status==='resolved'?'fruited':new Date(b.sealUntil||0)<=new Date()?'review':'growing',growthLogs:(b.reflections||[]).map(r=>({createdAt:r.date||now,text:r.content||String(r)})),legacySource:'worrybottle'})))}catch{}try{const worries=JSON.parse(localStorage.getItem('worries')||'[]');imported.push(...worries.map(w=>({id:`box-${w.id||uid()}`,title:(w.content||'一颗旧种子').slice(0,28),content:w.content||'',tag:w.tags?.[0]||'其他',intensity:w.emotion==='😫'?3:w.emotion==='😌'?1:2,createdAt:w.createTime||now,nextReviewAt:w.openTime||now,status:w.solved?'fruited':new Date(w.openTime||0)<=new Date()?'review':'growing',growthLogs:[],legacySource:'worrybox'})))}catch{}if(imported.length){seeds=imported;localStorage.setItem(STORE,JSON.stringify(seeds));toast(`已安全迁移 ${imported.length} 条旧记录`)}}
function render(){const list=$('#seedList');const today=new Date();seeds.forEach(s=>{if(s.status==='growing'&&new Date(s.nextReviewAt)<=today)s.status='review'});const visible=filter==='all'?seeds:seeds.filter(s=>s.status===filter);list.innerHTML='';$('#emptyState').hidden=visible.length>0;visible.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).forEach(seed=>{const [label,icon]=stage(seed);const card=document.createElement('article');card.className='seed-card';card.tabIndex=0;card.innerHTML=`<div class="stage-art" aria-hidden="true">${icon}</div><div><h3>${esc(seed.title)}</h3><p>${esc(seed.content).slice(0,72)}</p><div class="card-stage">${label}</div></div><div class="review-date">${seed.status==='fruited'?'完成于':'下次回访'}<br>${fmt(seed.status==='fruited'?seed.resolvedAt:seed.nextReviewAt)}</div>`;card.onclick=()=>openDetail(seed.id);card.onkeydown=e=>{if(e.key==='Enter')openDetail(seed.id)};list.append(card)});localStorage.setItem(STORE,JSON.stringify(seeds))}
function esc(v=''){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2300)}
function openEditor(){pendingAudio=null;$('#seedForm').reset();$('#audioPreview').hidden=true;$('#editorDialog').showModal()}
async function startRecording(){if(!navigator.mediaDevices?.getUserMedia){toast('当前浏览器不支持录音，请使用文字记录');openEditor();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];seconds=0;recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());pendingAudio=new Blob(chunks,{type:recorder.mimeType});const url=URL.createObjectURL(pendingAudio);$('#recordedAudio').src=url;$('#audioDuration').textContent=`录音 ${seconds} 秒`;$('#audioPreview').hidden=false;$('#editorDialog').showModal()};recorder.start();$('#recordButton').classList.add('recording');timer=setInterval(()=>{seconds++;$('#recordLabel').textContent=`正在录音 ${seconds}/60 秒`;if(seconds>=60)stopRecording()},1000);if(!recordingRequested)stopRecording()}catch{toast('没有获得麦克风权限，可改用文字记录')}}
function stopRecording(){if(!recorder||recorder.state==='inactive')return;clearInterval(timer);recorder.stop();$('#recordButton').classList.remove('recording');$('#recordLabel').textContent='按住录音'}
function openDetail(id){currentSeed=seeds.find(s=>s.id===id);if(!currentSeed)return;const [label]=stage(currentSeed);$('#detailStage').textContent=label;$('#detailTitle').textContent=currentSeed.title;$('#detailContent').textContent=currentSeed.content;$('#growthTimeline').innerHTML=`<div class="timeline-item"><time>${fmt(currentSeed.createdAt)}</time><p>种下这颗种子。</p></div>${(currentSeed.growthLogs||[]).map(l=>`<div class="timeline-item"><time>${fmt(l.createdAt)}</time><p>${esc(l.text)}</p></div>`).join('')}`;$('#progressForm').hidden=currentSeed.status==='fruited';$('#detailDialog').showModal()}

$('#seedForm').addEventListener('submit',async e=>{e.preventDefault();const title=$('#seedTitle').value.trim();const content=$('#seedContent').value.trim();if(!title||!content){toast('请补充种子的名字和内容');return}const seed={id:uid(),title,content,tag:$('#seedTag').value,intensity:Number(new FormData(e.target).get('intensity')),createdAt:new Date().toISOString(),nextReviewAt:addDays($('#reviewDays').value),status:'growing',growthLogs:[]};if(pendingAudio){seed.hasAudio=true;await putAudio(seed.id,pendingAudio)}seeds.push(seed);save();$('#editorDialog').close();toast('种子已经种下')});
$('#progressForm').addEventListener('submit',e=>{e.preventDefault();const text=$('#progressText').value.trim();if(!text)return toast('先写下这次的变化');currentSeed.growthLogs.push({createdAt:new Date().toISOString(),text});currentSeed.status='growing';currentSeed.nextReviewAt=addDays(7);$('#progressText').value='';save();$('#detailDialog').close();toast('新的变化已经长进年轮')});
$('#resolveButton').onclick=()=>{const text=$('#progressText').value.trim();if(text)currentSeed.growthLogs.push({createdAt:new Date().toISOString(),text});currentSeed.status='fruited';currentSeed.resolvedAt=new Date().toISOString();save();$('#detailDialog').close();toast('这颗种子已经结出果实')};
$$('.status-tab').forEach(btn=>btn.onclick=()=>{$$('.status-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');filter=btn.dataset.filter;$('#seed-list-title').textContent=btn.textContent.trim();render()});
$('#newTextSeed').onclick=openEditor;$('#closeEditor').onclick=()=>$('#editorDialog').close();$('#recordButton').addEventListener('pointerdown',e=>{e.preventDefault();recordingRequested=true;startRecording()});$('#recordButton').addEventListener('pointerup',()=>{recordingRequested=false;stopRecording()});$('#recordButton').addEventListener('pointercancel',()=>{recordingRequested=false;stopRecording()});$('[data-close-detail]').onclick=()=>$('#detailDialog').close();

function putAudio(id,blob){return new Promise((resolve,reject)=>{const req=indexedDB.open('WorrySeedAudio',1);req.onupgradeneeded=()=>req.result.createObjectStore('audio');req.onerror=()=>reject(req.error);req.onsuccess=()=>{const tx=req.result.transaction('audio','readwrite');tx.objectStore('audio').put(blob,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)}})}
load();
